"preserve_hierarchy": true
"commit_message": "[ci skip]"
"files": [
  {
    "source": "/core/src/main/resources/languages/en.yml",
    "translation": "/core/src/main/resources/languages/%locale%.yml",
    "type": "yaml"
  }
]