language: java

jdk:
  - openjdk8
  - openjdk11

jobs:
  include:
    - stage: "Build Parent"
      script:
        - mvn -pl . clean install
    - stage: "Build Core"
      script:
        - cd core
        - mvn clean install
    - stage: "Build Plugin"
      script:
        - cd bukkit
        - mvn clean verify

cache:
  directories:
    - $HOME/.m2