language: java

jdk:
  - openjdk8

jobs:
  include:
    - stage: "Build Parent"
      script:
        - mvn -pl . clean install
    - stage: "Build Plugin"
      script:
        - cd spigot
        - mvn clean verify

cache:
  directories:
    - $HOME/.m2