"commit_message": "[ci skip]"
"files": [
  {
    "source": "/core/src/main/resources/languages/en_US.yml",
    "translation": "/core/src/main/resources/languages/%locale_with_underscore%.yml",
    "export_only_approved": true,
    "type": "yaml",
    "ignore": [
        "/core/src/main/resources/languages/en_US.yml"
    ]
  }
]