name: CraftHeads
version: ${project.version}
main: me.deejayarroba.craftheads.Main
softdepend: [ Vault ]
authors: [ DeejayArroba, ursinn ]
description: ${project.description}
website: ${project.url}
api-version: 1.13
permissions:
  craftheads.*:
    description: Gives access to all of CraftHeads features
    children:
      craftheads.use: true
      craftheads.updater: true
  craftheads.use:
    description: Gives access to the CraftHeads menu
    default: op
  craftheads.updater:
    description: Gives access to CraftHeads updates
    default: op
